include:
  - board: akdk_bt1
    shield: split_ortho4x6_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: split4x6_l
  - board: akdk_bt1
    shield: split_ortho4x6_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: split4x6_r
  - board: akdk_bt1
    shield: settings_reset
    artifact-name: reset
